#!/bin/bash
cd /sys/kernel/config/usb_gadget/
mkdir -p neonode
cd neonode
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
mkdir -p strings/0x409
echo "fedcba9876543210" > strings/0x409/serialnumber
echo "Neonode" > strings/0x409/manufacturer
echo "Neonode Sensor USB Device" > strings/0x409/product
mkdir -p configs/c.1/strings/0x409
echo "Config 1: ECM network" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower

# Add functions here
mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol
echo 1 > functions/hid.usb0/subclass

# Keyboard
# echo 8 > functions/hid.usb0/report_length
# echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.usb0/report_desc

# Relative mouse
    # 0x05, 0x01,                    // USAGE_PAGE (Generic Desktop)
    # 0x09, 0x02,                    // USAGE (Mouse)
    # 0xa1, 0x01,                    // COLLECTION (Application)
    # 0x09, 0x01,                    //   USAGE (Pointer)
    # 0xa1, 0x00,                    //   COLLECTION (Physical)
    # 0x05, 0x09,                    //     USAGE_PAGE (Button)
    # 0x19, 0x01,                    //     USAGE_MINIMUM (Button 1)
    # 0x29, 0x03,                    //     USAGE_MAXIMUM (Button 3)
    # 0x15, 0x00,                    //     LOGICAL_MINIMUM (0)
    # 0x25, 0x01,                    //     LOGICAL_MAXIMUM (1)
    # 0x95, 0x03,                    //     REPORT_COUNT (3)
    # 0x75, 0x01,                    //     REPORT_SIZE (1)
    # 0x81, 0x02,                    //     INPUT (Data,Var,Abs)
    # 0x95, 0x01,                    //     REPORT_COUNT (1)
    # 0x75, 0x05,                    //     REPORT_SIZE (5)
    # 0x81, 0x03,                    //     INPUT (Cnst,Var,Abs)
    # 0x05, 0x01,                    //     USAGE_PAGE (Generic Desktop)
    # 0x09, 0x30,                    //     USAGE (X)
    # 0x09, 0x31,                    //     USAGE (Y)
    # 0x15, 0x81,                    //     LOGICAL_MINIMUM (-127)
    # 0x25, 0x7f,                    //     LOGICAL_MAXIMUM (127)
    # 0x75, 0x08,                    //     REPORT_SIZE (8)
    # 0x95, 0x02,                    //     REPORT_COUNT (2)
    # 0x81, 0x06,                    //     INPUT (Data,Var,Rel)
    # 0xc0,                          //   END_COLLECTION
    # 0xc0                           // END_COLLECTION
# echo 3 > functions/hid.usb0/report_length
# echo -ne \\x05\\x01\\x09\\x02\\xa1\\x01\\x09\\x01\\xa1\\x00\\x05\\x09\\x19\\x01\\x29\\x03\\x15\\x00\\x25\\x01\\x95\\x03\\x75\\x01\\x81\\x02\\x95\\x01\\x75\\x05\\x81\\x03\\x05\\x01\\x09\\x30\\x09\\x31\\x15\\x81\\x25\\x7f\\x75\\x08\\x95\\x02\\x81\\x06\\xc0\\xc0 > functions/hid.usb0/report_desc

# Absolute mouse
    # 0x05, 0x01,                    // USAGE_PAGE (Generic Desktop)
    # 0x09, 0x02,                    // USAGE (Mouse)
    # 0xa1, 0x01,                    // COLLECTION (Application)
    # 0x09, 0x01,                    //   USAGE (Pointer)
    # 0xa1, 0x00,                    //   COLLECTION (Physical)
    # 0x05, 0x09,                    //     USAGE_PAGE (Button)
    # 0x19, 0x01,                    //     USAGE_MINIMUM (Button 1)
    # 0x29, 0x03,                    //     USAGE_MAXIMUM (Button 3)
    # 0x15, 0x00,                    //     LOGICAL_MINIMUM (0)
    # 0x25, 0x01,                    //     LOGICAL_MAXIMUM (1)
    # 0x95, 0x03,                    //     REPORT_COUNT (3)
    # 0x75, 0x01,                    //     REPORT_SIZE (1)
    # 0x81, 0x02,                    //     INPUT (Data,Var,Abs)
    # 0x95, 0x01,                    //     REPORT_COUNT (1)
    # 0x75, 0x05,                    //     REPORT_SIZE (5)
    # 0x81, 0x03,                    //     INPUT (Cnst,Var,Abs)
    # 0x05, 0x01,                    //     USAGE_PAGE (Generic Desktop)
    # 0x09, 0x30,                    //     USAGE (X)
    # 0x09, 0x31,                    //     USAGE (Y)
    # 0x16, 0x00, 0x00,              //     LOGICAL_MINIMUM (0)
    # 0x26, 0xff, 0x7f,              //     LOGICAL_MAXIMUM (32767)
    # 0x75, 0x10,                    //     REPORT_SIZE (16)
    # 0x95, 0x02,                    //     REPORT_COUNT (2)
    # 0x81, 0x02,                    //     INPUT (Data,Var,Abs)
    # 0xc0,                          //   END_COLLECTION
    # 0xc0                           // END_COLLECTION
echo 5 > functions/hid.usb0/report_length
echo -ne \\x05\\x01\\x09\\x02\\xa1\\x01\\x09\\x01\\xa1\\x00\\x05\\x09\\x19\\x01\\x29\\x03\\x15\\x00\\x25\\x01\\x95\\x03\\x75\\x01\\x81\\x02\\x95\\x01\\x75\\x05\\x81\\x03\\x05\\x01\\x09\\x30\\x09\\x31\\x16\\x00\\x00\\x26\\xff\\x7f\\x75\\x10\\x95\\x02\\x81\\x02\\xc0\\xc0 > functions/hid.usb0/report_desc

ln -s functions/hid.usb0 configs/c.1/
# End functions

ls /sys/class/udc > UDC